//Code generated by App Designer
{
int notifyId = SketchwareUtil.getRandom((int)(0), (int)(99999));
NotificationManager mNotificationManager = (NotificationManager) getSystemService(Context.NOTIFICATION_SERVICE);
Notification.Builder mbuilder = new Notification.Builder(MainActivity.this);
mbuilder.setSmallIcon(R.drawable.default_image);
mbuilder.setContentTitle("Leomodz");
mbuilder.setContentText("new version please update......");
mbuilder.setShowWhen(false);
mbuilder.setDefaults( Notification.DEFAULT_SOUND | Notification.DEFAULT_VIBRATE);
mbuilder.setOngoing(true);
mbuilder.setColor(Color.parseColor("#2196F3"));
if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
		String channelId1 = "notifications";
		String channelName1 = "Notifications";
		NotificationChannel channel = new NotificationChannel(channelId1, channelName1, NotificationManager.IMPORTANCE_DEFAULT);
		channel.enableLights(true);
		channel.setLightColor(Color.BLUE);
		channel.setShowBadge(true);
		channel.enableVibration(true);
		mbuilder.setChannelId(channelId1);
		if (mNotificationManager != null) {
				mNotificationManager.createNotificationChannel(channel);
		}
} else {
		mbuilder.setDefaults(Notification.DEFAULT_SOUND | Notification.DEFAULT_LIGHTS | Notification.DEFAULT_VIBRATE);
}
if (mNotificationManager != null) {
		mNotificationManager.notify(notifyId, mbuilder.build());
}
}
